Path = 'f358cac4f944406e90abe9f1b69ce651'
ELASTIC_PASSWORD = "=hExbx*huLo1-vtaISC="
CERT_FINGERPRINT = "fc8723950846b914100ffb20ff3e9458e1b7f48173c262aba649bae51fbfc76e"
aws_access_key_id="AKIAVOD5X2XTVVGHUF34"
aws_secret_access_key="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"
bing_key="eb8ebc70665844bb87bea3552f62b57d"
bing_web_ep="https://api.bing.microsoft.com/v7.0/search"
bing_visual_ep="https://api.bing.microsoft.com/bing/v7.0/images/visualsearch"
